services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: upb
      POSTGRES_HOST: 127.0.0.1
    ports:
      - "5432:5432/tcp"